### PR TITLE
Fix problems related to multiple options with the same value

### PR DESCRIPTION
**Pull request by s-eckard**

### CODE REVIEW

**Review by tiesont — COMMENTED** [review]
Thanks for your effort on this. Is there anything I can do to help with completing this?

**Comment by s-eckard** [comment]
@tiesont: If you like you could also review the changes. I don't just want to merge them after I'm not totally convinced of my solution.

**Comment by tiesont** [comment]
> 
> 
> @tiesont: If you like you could also review the changes. I don't just want to merge them after I'm not totally convinced of my solution.

I did give it a once-over, but I'll pull down the changes and take a closer look. At the moment, though, nothing stood out as a potential problem.

**Comment by davidstutz** [comment]
Looks very good to me. Just some minor things I want to understand before merging:
* In lines 905 and 1066, the `&& this.options.multiple` is removed. I do not see a reason why it would stay, just want to check whether this was intentional?
* Can you explain the if statement in line 961? As far as I can see the difference is between normal options and the select all option.
* Lines 1359ff also seem to be new, what's the reason behind the if statement?
Also nice job in adding tests and refactoring some parts in terms of coding style!

**Comment by s-eckard** [comment]
1. The `this.options.multiple` was removed to support collapsible optGroups for single selects. When I tested it, the groups worked fine for single selects and I couldn't see a reason to hide this feature.
2. These lines add to each checkboxes in the multiselect a unique ID which enables us to also set the `for`-attribute of the label correctly. This ID is the core to be able to resolve options by ID instead of by value. This is also done for the select all checkbox even if here the only benefit is to now have the `for`-attribute.
3. This was just added to prevent out-of-range errors. I had this once during development and added it because this method should not brake the multiselect. But usually it should happen that we run into this case.

**Comment by davidstutz** [comment]
Ok, thanks. Makes sense, never had this out of range error before though, so great catch.

**Review by davidstutz — APPROVED** [review]

**Pull request merged**
