### PR TITLE
Added TypeScript definition.

### PR DESCRIPTION
**Pull request by mak0t0san**
I would like to use this library from TypeScript but could not find any TypeScript definition file for it.  I took the time to create one base on the documentation on the site.

### CODE REVIEW

**Comment by gs-akhan** [comment]
Hi, please merge this. 
Thanks

**Comment by taoqf** [comment]
I need this, too.

**Comment by eman1986** [comment]
I'd love to see this available

**Comment by gs-akhan** [comment]
@davidstutz if you can make me contributor of the repo, I can help in merging issues and stuff.

Thanks

**Comment by gs-akhan** [comment]
@davidstutz This won't break any thing.. :)

**Pull request merged**
