### PR TITLE
Make numberDisplayed disableable

### PR DESCRIPTION
**Pull request by zimmski**
It is not often, that you can write the word disableable, and sometimes you just want to disable a feature, like numberDisplayed, which gives you the opportunity, nah, the privilege to write disableable.

### CODE REVIEW

**Comment by zimmski** [comment]
@davidstutz can I get this merged?

**Comment by zimmski** [comment]
@davidstutz I am looking again at open PRs of mine. This one is open for almost a year even though it changes just a single line. Is this repository still maintained?

**Comment by zimmski** [comment]
@davidstutz Any update on this?

**Comment by davidstutz** [comment]
Sorry for the really late reply. Will merge it, thanks for the PR ;)

**Pull request merged**
